### ISSUE TITLE
OoS: Softlocked in Woods of Winter

### ISSUE THREAD

**Issue by 03bgood** [jangler/oracles-randomizer#150]
I have the Rod of Seasons, but it only changes the season to Autumn. Both paths outside of WoW lead to Autumn trees blocking me and there's no way to get out without changing the season to Winter, which I cannot do since I don't have the Winter ability. How do I teleport back to Horon Village without the Gale Seeds?

These are the only items I have:

Wooden Sword (L-1)
Roc's Feather (L-1)
Bombs (10)
Rod of Seasons + Autumn
Zora's Flippers

Seed #: 69A70900+TPK

**Comment by ReggX** [comment]
1. Since you have a seed with +T (treewarp enabled), you can open up the map (select), hold the start button, and exit the map while still holding the start button. That will warp you back to the village.

2. Looking at the items you have, I guess you got into Woods of Winter by diving down from Sunken City. That should have displayed a softlock warning as soon as you got near the diving spot which warned you about this very thing happening!

3. If you have questions about progression and softlocks, please use the Oracles Discord server first. There are a lot more people who will notice your question than in the github bug tracker. https://discord.gg/pyBEbz5
