### ISSUE TITLE
Support for Analogue .pocket ROM export?

### ISSUE THREAD

**Issue by mysterypaint** [jangler/oracles-randomizer#162]
Hello! I recently just tried to play OoS Rando on an Analogue Pocket.

It works great!... But without a proper flashcart (My Everdrive X7 will not work [without soldering](https://www.youtube.com/watch?v=GosNJKktOzY)), I must run Rando using an unofficial GBC core, which doesn't allow for features that the official Analogue Pocket cores provide, including several display/color saturation options.

To mitigate the issue above, the Analogue Pocket community creates .ips ".pocket" patches for individual games to support the official cores natively: https://github.com/treyturner/analogue-pocket-patches/blob/main/TUTORIAL.md

Can we get ``.pocket`` ROM-format export support for this randomizer? I tried to patch an OoS Randomizer Rom with the vanilla OoS' .pocket patch: https://www.reddit.com/r/AnaloguePocket/comments/rqymiq/legend_of_zelda_oracle_of_agesseasons_pocket/

https://github.com/Infinest/oracles-disasm/commit/e89d7026ad22a1619f3939eac8fad82cbc5d4e18

Unfortunately, however, the vanilla ``.pocket`` patch seems to be incompatible with Randomizer: After loading into the game, Link seems to fall seemingly forever, softlocking the game.

Thank you for your time and consideration!

**Comment by jangler** [comment]
Hi there, a couple of questions:

- Which version of the patches are you using? That Reddit post links v1.1, but I see in the comments on the linked commit that there is at least a v1.2 that fixes errors present in earlier versions.
- Which version of the randomizer are you using? Since this is a frequent source of confusion.

I wouldn't expect a clean patch to be incompatible with my version of the randomizer, since I don't think my randomizer code touches anything that uses LCDC or STAT. Drenn's randomizer would be a different beast.

**Comment by mysterypaint** [comment]
You're absolutely right: Patching the ROM with v1.2 after randomizing the ROM (Rando v4.1.6 in this case) works properly!

For anyone else reading: v1.2 for both Ages + Seasons can be downloaded here: https://github.com/Infinest/oracles-disasm/commit/e89d7026ad22a1619f3939eac8fad82cbc5d4e18#r63147260

Thank you again for pointing out that v1.2 patch; it works flawlessly!
