### ISSUE TITLE
Swimming through currents

### ISSUE THREAD

**Issue by Drenn1** [jangler/oracles-randomizer#81]
It's possible to swim through currents with only flippers, if you have god-tier timing or mashing. This is probably too stupid even for hard mode, though, so perhaps it should be stated that this isn't in the logic.

**Comment by jangler** [comment]
I think I'll document all the things I can remember that are known but still not in hard logic. They should go somewhere separate from the "notes" files, since they'll contain things that only a few people in existence are even aware of, and I want the notes to be short enough that there's a chance people will actually read them.

**Comment by jangler** [comment]
Added this to https://wiki.zeldahacking.net/oracle/Randomizer_tricks .
