### ISSUE TITLE
Randomized dungeon entrances

### ISSUE THREAD

**Issue by Drenn1** [jangler/oracles-randomizer#85]
This would be a (relatively) easy way to add some variety. Since many dungeons are locked until you find a key in a haystack, while others have many ways to access them, it would be nice for the more readily accessible dungeons to change from run to run.

**Comment by jangler** [comment]
This is definitely one of the location randomization options I'd be warmest towards. I guess seasons D2's two side entrances would need to remain the same.

But now we start getting into my dreaded "option" territory, since randomizing dungeon entrances could make things a lot more inconvenient, and make seeds take longer. I'm thinking about ages D6 entrances being far away from each other, and the D8 entrances in both games taking a long time just to reach to find out what it is.

**Comment by jangler** [comment]
4.x could have this feature, since 4.x versions will be about options. I wouldn't be especially keen on playing randomized dungeon seeds, but it wouldn't be very difficult to implement either.

**Comment by jangler** [comment]
Alternate D2 entrances in seasons should just be gone in this game mode, and the staircases to the alternate entrances should be directly linked instead.

**Comment by jangler** [comment]
For bookkeeping purposes – this is implemented as of 5ab374e, and will be included in 4.0
